---
kind: pipeline
name: "Push"

concurrency:
  limit: 2

---
kind: pipeline
name: "New version"

concurrency:
  limit: 2

steps:
  - name: "Build Docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
      tags: ${DRONE_COMMIT:0:7}

  - name: "Build custom baseapp with assembly line"
    image: curlimages/curl
    environment:
      SERVER: https://ci.openware.work
      REPO: openware/assembly-line
      BRANCH: master
      COMPONENT: baseapp
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - COMPONENT_VERSION=$(cat .tags)
      - "curl -s -XPOST -H \"Authorization: Bearer $DRONE_TOKEN\" -i \"$SERVER/api/repos/$REPO/builds?branch=$BRANCH&ASSEMBLY_COMPONENT_VERSION=$COMPONENT_VERSION&ASSEMBLY_COMPONENT=$COMPONENT\""

trigger:
  branch:
    - master
    - "*-stable"
    - "integration/*"
    - "hotfix/*"
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
